### ISSUE TITLE
script gives error at make zm part.

### ISSUE THREAD

**Issue by alco28** [kylejohnson/puppet-zoneminder#2]
Script works until the part where zoneminder make runs.
the next error appears in the command line:

---

In file included from zm_rtsp.cpp:29:0:
zm_sdp.h:44:14: fout: use of enum âCodecIDâ without previous declaration
zm_sdp.h:53:14: fout: use of enum âCodecIDâ without previous declaration
make[2]: **\* [zm_rtsp.o] Fout 1
make[2]: Map '/usr/local/src/zoneminder/src' wordt verlaten
make[1]: **\* [all-recursive] Fout 1
make[1]: Map '/usr/local/src/zoneminder' wordt verlaten
make: **\* [all] Fout 2
root@zoneminder:/usr/local/src/zoneminder# dir

---

I looked into the zm_sdp.h file but it lookes like the orginal..so why the crash? perhaps the fffmpeg version?

**Comment by kylejohnson** [comment]
This is probably failing due to either the ffmpeg or the libjpeg version.  I'll check it out.
