### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by cotman** [kylejohnson/puppet-zoneminder#8]
Hi,

More of a question this really, so apologies in advance for posting here...

I've had an install of what's identified as version 1.26.3 since your puppet module was available, and all has been great.

However how, using the puppet wrapper, do I go about upgrading to pick-up and install changes in the main Zoneminder repo since my install?

Thanks.

**Comment by kylejohnson** [comment]
No worries.  The puppet script doesn't handle upgrades - it is for getting a ZoneMinder server up and running ASAP.

With that said, you can upgrade manually.

1: Download the source from the zoneminder git repo
2: Compile the source and install the source (e.g. ./configure && make && sudo make install)
3: Upgrade the DB:  sudo zmupdate.pl

Hope this helps.  Stop by #zoneminder on irc freenode if you need help.
